name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'iac/**'
      - 'docs/**'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'iac/**'
      - 'docs/**'
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint code
        run: |
          flake8 .

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest test_helper.py

  build:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: roka2205/challenge-latam:${{ github.sha }}

  deploy:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: google auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy challenge-latam-api \
            --image roka2205/challenge-latam:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --service-account cloud-run-service-account@${{ vars.GCP_PROJECT }}.iam.gserviceaccount.com \
            --set-env-vars GCP_PROJECT=${{ vars.GCP_PROJECT }},PUBSUB_TOPIC=${{ vars.PUBSUB_TOPIC }},BQ_DATASET=${{ vars.BQ_DATASET }},BQ_TABLE=${{ vars.BQ_TABLE }}

  integration-test:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run integration tests
        env:
          CLOUD_RUN_URL: ${{ vars.CLOUD_RUN_URL }}
        run: |
          python test_integration.py

